version: '3.7'
services:
  honyaku:
    container_name: honyaku
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    environment: []
    depends_on: []
    command: cargo watch -x "run" -w src
    tty: true
